version: "3"

services:
  auth_app:
    build:
      context: .
    ports:
      - "8888:8080"
      - "8000:8080"
      - "5678:5678"
    volumes:
      - ./:/app
      # sh -c "sleep 1 &&
    command: >
      sh -c "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8080 "

    environment:
      - DB_HOSTNAME=auth_db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=MyStr0ngP@SS
      - DB_DBNAME=authdb

    depends_on:
      - auth_db

  auth_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyStr0ngP@SS
    volumes:
      - /home/ubuntu/development/poc/dbvol/authtokenapi:/var/lib/postgresql/data
    ports:
      - 5432:5432

  auth_nginx:
    image: nginx:latest
    container_name: auth_nginx
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/cert/:/etc/sslcert/:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth_app:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    depends_on: 
      - auth_app
      - auth_db